Vagrant.configure("2") do |config|
    # skip vbguest
    config.vbguest.auto_update = false
    # Guest VM Name, CentOS version for base box, shared folder
    vm_name = 'node2.test014.org'
    vagrant_arg = ARGV[0]
    config.vm.box = "centos/7"
    config.vm.box_version = "2004.01"
    
    # Guest VM settings
    config.vm.provider "vmware_desktop" do |v|
        v.vmx["memsize"] = "4096"
        v.vmx["numvcpus"] = "4"
        v.vmx["ethernet0.pcislotnumber"] = "32"
    end

    config.vm.network "private_network", ip: "192.168.3.12"
    config.vm.hostname = vm_name

    config.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "provisioning/vagrant_playbook.yml"
        ansible.verbose = "v"
    end
    config.vm.provision :reload 
end
